package co.org.profamilia.agendamiento.dto.wrapper.impl;
// Generated 15-ene-2018 21:43:54 by Hibernate Tools 3.2.2.GA

import co.org.profamilia.agendamiento.dto.DiaProgramacionDTO;
import co.org.profamilia.agendamiento.dto.wrapper.AbstractWrapperDiaDTO;
import co.org.profamilia.agendamiento.dto.wrapper.DiaDTO;
import java.math.BigDecimal;
import java.text.ParseException;
import java.util.Date;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * DiaProgramacionDTO generated by hbm2java
 */
public class WrapperDiaProgramacionDTO extends AbstractWrapperDiaDTO<DiaProgramacionDTO,WrapperDiaProgramacionDTO> {

    private static final Logger logger = LoggerFactory.getLogger(WrapperDiaProgramacionDTO.class);

    public WrapperDiaProgramacionDTO(DiaProgramacionDTO dto) {
        super(dto);
    }
    
    @Override
    public Long getId() {
        return (this.dto != null) ? this.dto.getId() : null;
    }

    @Override
    public void setId(Long id) {
        this.dto.setId(id);
    }

    @Override
    public Boolean getHabil() {
        return this.dto.getHabil().intValue() > 0;
    }

    @Override
    public void setHabil(Boolean habil) {
        if (this.dto != null) {
            if (habil) {
                this.dto.setHabil(1l);
            } else {
                this.dto.setHabil(0l);
            }
        }
    }

    @Override
    public Long getDia() {
        Long dia = (this.dto != null) ? this.dto.getDia() : null;
        return dia;
    }

    @Override
    public void setDia(Long dia) {
        if (this.dto != null) {
            this.dto.setDia(dia);
        }
    }

    @Override
    public Date getHoraInicio() throws ParseException {
        return (this.dto != null && this.dto.getHoraInicio() != null) ? convertStringHourToDate(dto.getHoraInicio()) : null;
    }

    @Override
    public void setHoraInicio(Date horaInicio) {
        if (this.dto != null) {
            this.dto.setHoraInicio(convertDateToStringHour(horaInicio));
        }
    }

    @Override
    public Date getHoraFin() throws ParseException {
        return (this.dto != null && this.dto.getHoraFin() != null) ? convertStringHourToDate(dto.getHoraFin()) : null;
    }

    @Override
    public void setHoraFin(Date horaFin) {
        if (this.dto != null) {
            this.dto.setHoraFin(convertDateToStringHour(horaFin));
        }
    }
    

    public Date getHoraInicioAlmuerzo() throws ParseException {
        return (this.dto != null && 
                ((DiaProgramacionDTO)this.dto).getHoraInicioAlmuerzo() != null) ? 
                convertStringHourToDate(((DiaProgramacionDTO)this.dto).getHoraInicioAlmuerzo()) : null;
    }

    public void setHoraInicioAlmuerzo(Date horaInicioAlmuerzo) {
        if (this.dto != null) {
            ((DiaProgramacionDTO)this.dto).setHoraInicioAlmuerzo(convertDateToStringHour(horaInicioAlmuerzo));
        }
    }

    public Date getHoraFinAlmuerzo() throws ParseException {
        return (this.dto != null && 
                ((DiaProgramacionDTO)this.dto).getHoraFinAlmuerzo() != null) ? 
                convertStringHourToDate(((DiaProgramacionDTO)this.dto).getHoraFinAlmuerzo()) : null;
    }

    public void setHoraFinAlmuerzo(Date horaFinAlmuerzo) {
        if (this.dto != null) {
            ((DiaProgramacionDTO) this.dto).setHoraFinAlmuerzo(convertDateToStringHour(horaFinAlmuerzo));
        }
    }
    
    @Override
    public int compareTo(WrapperDiaProgramacionDTO o) {

        if (this == null) {
            return o == null ? 0 : 1;
        }

        if (o == null) {
            return 1;
        }

        if (this.getDia() == null) {
            return o.getDia() == null ? 0 : 1;
        }

        if (o.getDia() == null) {
            return 1;
        }

        return this.getDia().compareTo(o.getDia());
    }
    
    public static void main(String[] args) {

        WrapperDiaProgramacionDTO wrapper = new WrapperDiaProgramacionDTO(new DiaProgramacionDTO());

        System.out.println(wrapper.getDto());

        Date d = new Date();

        System.out.println(d);
        wrapper.setHoraFin(d);
        wrapper.getDia();
        System.out.println(wrapper.getDto().getHoraFin());

    }

    

}
